"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*fiu+@jpx&e8&g-=0m!0docy$a^%2or%&64_zbv30f52ny8_t5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'about.apps.AboutConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'
APPEND_SLASH = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST_FRAMEWORK = {
#     'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
#     'DEFAULT_VERSION': 'v1',
#     'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',),
#     # support both session and token auth for dev and staging, cos docs
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'DEFAULT_PAGINATION_CLASS': 'fieldstone.pagination.LimitOffsetPagination',
#     'EXCEPTION_HANDLER': 'fieldstone.exceptions.exception_handler',
#     'DEFAULT_RENDERER_CLASSES': (
#         'fieldstone.renderers.SafeBigIntegersJSONRenderer',
#         'fieldstone.renderers.IndentedJSONRenderer',
#     ),
#     # liberal rate limiting by default to not impede regular usage
#     # but deter abuse
#     'DEFAULT_THROTTLE_CLASSES': (
#         'fieldstone.throttling.UserBurstRateThrottle',
#         'fieldstone.throttling.UserSustainedRateThrottle',
#         'fieldstone.throttling.AnonBurstRateThrottle',
#         'fieldstone.throttling.AnonSustainedRateThrottle',
#     ),
#     'DEFAULT_THROTTLE_RATES': {
#         'user-burst': '100/min',
#         'user-sustained': '1000/hour',
#         'anon-burst': '100/min',
#         'anon-sustained': '1000/hour',
#     },
#     # allow custom sections in our schema generation to enrich docs
#     'DEFAULT_SCHEMA_CLASS': 'fieldstone.docs.schemas.SubsectionSchema',
#     # use HTTP verbs as much as possible - this impacts docs rendering
#     'SCHEMA_COERCE_METHOD_NAMES': {
#         'partial_update': 'patch',
#         'destroy': 'delete',
#         'create': 'post',
#         'retrieve': 'get',
#         'update': 'put',
#     },
#     'TEST_REQUEST_DEFAULT_FORMAT': 'json',
#     'TEST_REQUEST_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#         # renderers allowing us to submit various types of data in tests
#         'fieldstone.tests.renderers.JPGRenderer',
#         'rest_framework.renderers.MultiPartRenderer',
#         'fieldstone.tests.renderers.MSWordRenderer',
#     ),
# }


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
